### ISSUE TITLE
Deployment is broken

### ISSUE THREAD

**Issue by berik** [keystonejs/keystone-6-heroku-example#5]
When you press button "Deploy to Heroku" it breaks at `keystone-next build && keystone-next prisma migrate deploy`

**Comment by ettmetal** [comment]
I'm also having broken deployment; this is the output I'm getting: https://pastebin.com/0vjZCnmt

**Comment by bladey** [comment]
Thanks @berik and @ettmetal, we're aware of this and looking into it.

**Comment by bladey** [comment]
This has now been resolved, Keystone has also been updated - https://github.com/keystonejs/keystone-6-heroku-example/commit/64db1553254bfc9377217fa6d246d47515ca01f8
